<a href="https://colab.research.google.com/github/HenryZumaeta/py4cd_EPC2025/blob/main/C23/C23_Script01_Regulaizacion_Lasso_Ridge_ElasticNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regresión Lineal

In [3]:
# Módulos y datos
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Datos: https://cdn.uci-ics-mlr-prod.aws.uci.edu/183/communities%2Band%2Bcrime.zip
os.system("wget https://cdn.uci-ics-mlr-prod.aws.uci.edu/183/communities%2Band%2Bcrime.zip")

0

In [4]:
# Descomprimimos el archivo zip+
os.system("unzip communities+and+crime.zip")

256

In [5]:
# Mostremos/observemos las primeras líneas de este dataset
!cat communities.data | head -n 5

8,?,?,Lakewoodcity,1,0.19,0.33,0.02,0.9,0.12,0.17,0.34,0.47,0.29,0.32,0.2,1,0.37,0.72,0.34,0.6,0.29,0.15,0.43,0.39,0.4,0.39,0.32,0.27,0.27,0.36,0.41,0.08,0.19,0.1,0.18,0.48,0.27,0.68,0.23,0.41,0.25,0.52,0.68,0.4,0.75,0.75,0.35,0.55,0.59,0.61,0.56,0.74,0.76,0.04,0.14,0.03,0.24,0.27,0.37,0.39,0.07,0.07,0.08,0.08,0.89,0.06,0.14,0.13,0.33,0.39,0.28,0.55,0.09,0.51,0.5,0.21,0.71,0.52,0.05,0.26,0.65,0.14,0.06,0.22,0.19,0.18,0.36,0.35,0.38,0.34,0.38,0.46,0.25,0.04,0,0.12,0.42,0.5,0.51,0.64,0.03,0.13,0.96,0.17,0.06,0.18,0.44,0.13,0.94,0.93,0.03,0.07,0.1,0.07,0.02,0.57,0.29,0.12,0.26,0.2,0.06,0.04,0.9,0.5,0.32,0.14,0.2
53,?,?,Tukwilacity,1,0,0.16,0.12,0.74,0.45,0.07,0.26,0.59,0.35,0.27,0.02,1,0.31,0.72,0.11,0.45,0.25,0.29,0.39,0.29,0.37,0.38,0.33,0.16,0.3,0.22,0.35,0.01,0.24,0.14,0.24,0.3,0.27,0.73,0.57,0.15,0.42,0.36,1,0.63,0.91,1,0.29,0.43,0.47,0.6,0.39,0.46,0.53,0,0.24,0.01,0.52,0.62,0.64,0.63,0.25,0.27,0.25,0.23,0.84,0.1,0.16,0.1,0.17,0.29,0.17,0.26,0.2,0.82,0,0.02,0.79,0.24,0.02,0.25,0.65,0.16,0,0.21,0.2,0.21,0.42,0.38,0.4,0.37,0.29,0.32,0.18,0,0,0.21,0.5,0.34,0.6,0.52,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0.02,0.12,0.45,?,?,?,?,0,?,0.67
24,?,?,Aberdeentown,1,0,0.42,0.49,0.56,0.17,0.04,0.39,0.47,0.28,0.32,0,0,0.3,0.58,0.19,0.39,0.38,0.4,0.84,0.28,0.27,0.29,0.27,0.07,0.29,0.28,0.39,0.01,0.27,0.27,0.43,0.19,0.36,0.58,0.32,0.29,0.49,0.32,0.63,0.41,0.71,0.7,0.45,0.42,0.44,0.43,0.43,0.71,0.67,0.01,0.46,0,0.07,0.06,0.15,0.19,0.02,0.02,0.04,0.05,0.88,0.04,0.2,0.2,0.46,0.52,0.43,0.42,0.15,0.51,0.5,0.01,0.86,0.41,0.29,0.3,0.52,0.47,0.45,0.18,0.17,0.16,0.27,0.29,0.27,0.31,0.48,0.39,0.28,0,0,0.14,0.49,0.54,0.67,0.56,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0.01,0.21,0.02,?,?,?,?,0,?,0.43
34,5,81440,Willingborotownship,1,0.04,0.77,1,0.08,0.12,0.1,0.51,0.5,0.34,0.21,0.06,1,0.58,0.89,0.21,0.43,0.36,0.2,0.82,0.51,0.36,0.4,0.39,0.16,0.25,0.36,0.44,0.01,0.1,0.09,0.25,0.31,0.33,0.71,0.36,0.45,0.37,0.39,0.34,0.45,0.49,0.44,0.75,0.65,0.54,0.83,0.65,0.85,0.86,0.03,0.33,0.02,0.11,0.2,0.3,0.31,0.05,0.08,0.11,0.11,0.81,0.08,0.56,0.62,0.85,0.77,1,0.94,0.12,0.01,0.5,0.01,0.97,0.96,0.6,0.47,0.52,0.11,0.11,0.24,0.21,0.19,0.75,0.7,0.77,0.89,0.63,0.51,0.47,0,0,0.19,0.3,0.73,0.64,0.65,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0.02,0.39,0.28,?,?,?,?,0,?,0.12
42,95,6096,Bethlehemtownship,1,0.01,0.55,0.02,0.95,0.09,0.05,0.38,0.38,0.23,0.36,0.02,0.9,0.5,0.72,0.16,0.68,0.44,0.11,0.71,0.46,0.43,0.41,0.28,0,0.74,0.51,0.48,0,0.06,0.25,0.3,0.33,0.12,0.65,0.67,0.38,0.42,0.46,0.22,0.27,0.2,0.21,0.51,0.91,0.91,0.89,0.85,0.4,0.6,0,0.06,0,0.03,0.07,0.2,0.27,0.01,0.02,0.04,0.05,0.88,0.05,0.16,0.19,0.59,0.6,0.37,0.89,0.02,0.19,0.5,0.01,0.89,0.87,0.04,0.55,0.73,0.05,0.14,0.31,0.31,0.3,0.4,0.36,0.38,0.38,0.22,0.51,0.21,0,0,0.11,0.72,0.64,0.61,0.53,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0.04,0.09,0.02,?,?,?,?,0,?,0.03

In [6]:
# Carguemos en memoria el conjunto de datos
df = pd.read_csv("communities.data", header=None, na_values="?")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Columns: 128 entries, 0 to 127
dtypes: float64(125), int64(2), object(1)
memory usage: 1.9+ MB

In [7]:
# Del archivo comunities.names vamos a obtener los nombres de las columnas

columns = []

with open("communities.names", "r") as f:
    for line in f:
        if line.startswith("@attribute"):
            columns.append(line.split()[1])

df.columns = columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Columns: 128 entries, state to ViolentCrimesPerPop
dtypes: float64(125), int64(2), object(1)
memory usage: 1.9+ MB

In [8]:
df.head()

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
0,8,NaN,NaN,Lakewoodcity,1,0.19,0.33,0.02,0.90,0.12,...,0.12,0.26,0.20,0.06,0.04,0.9,0.5,0.32,0.14,0.20
1,53,NaN,NaN,Tukwilacity,1,0.00,0.16,0.12,0.74,0.45,...,0.02,0.12,0.45,NaN,NaN,NaN,NaN,0.00,NaN,0.67
2,24,NaN,NaN,Aberdeentown,1,0.00,0.42,0.49,0.56,0.17,...,0.01,0.21,0.02,NaN,NaN,NaN,NaN,0.00,NaN,0.43
3,34,5.0,81440.0,Willingborotownship,1,0.04,0.77,1.00,0.08,0.12,...,0.02,0.39,0.28,NaN,NaN,NaN,NaN,0.00,NaN,0.12
4,42,95.0,6096.0,Bethlehemtownship,1,0.01,0.55,0.02,0.95,0.09,...,0.04,0.09,0.02,NaN,NaN,NaN,NaN,0.00,NaN,0.03

In [9]:
# Veamos qué columnas tienen valores faltantes
df.isnull().sum().sort_values(ascending=False)

PolicBudgPerPop        1675
LemasGangUnitDeploy    1675
LemasPctPolicOnPatr    1675
PolicCars              1675
PolicOperBudg          1675
                       ...
LandArea                  0
PopDens                   0
PctUsePubTrans            0
LemasPctOfficDrugUn       0
ViolentCrimesPerPop       0
Length: 128, dtype: int64

In [10]:
# Primer escenario: Eliminar a las filas con valores faltantes
df.dropna(axis = 0)

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
16,36,1.0,1000.0,Albanycity,1,0.15,0.31,0.40,0.63,0.14,...,0.06,0.39,0.84,0.06,0.06,0.91,0.5,0.88,0.26,0.49
23,19,193.0,93926.0,SiouxCitycity,1,0.11,0.43,0.04,0.89,0.09,...,0.16,0.12,0.07,0.04,0.01,0.81,1.0,0.56,0.09,0.63
33,51,680.0,47672.0,Lynchburgcity,1,0.09,0.43,0.51,0.58,0.04,...,0.14,0.11,0.19,0.05,0.01,0.75,0.0,0.60,0.10,0.31
68,34,23.0,58200.0,PerthAmboycity,1,0.05,0.59,0.23,0.39,0.09,...,0.01,0.73,0.28,0.00,0.02,0.64,0.0,1.00,0.23,0.50
74,9,9.0,46520.0,Meridentown,1,0.08,0.39,0.08,0.85,0.04,...,0.07,0.21,0.04,0.02,0.01,0.70,1.0,0.44,0.11,0.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,34,39.0,40350.0,Lindencity,10,0.04,0.39,0.39,0.65,0.09,...,0.03,0.28,0.32,0.02,0.01,0.85,0.0,0.99,0.19,0.22
1963,36,27.0,59641.0,Poughkeepsiecity,10,0.03,0.32,0.61,0.47,0.09,...,0.01,0.47,0.42,0.07,0.08,0.49,0.0,0.37,1.00,0.45
1981,9,9.0,35650.0,Hamdentown,10,0.07,0.38,0.17,0.84,0.11,...,0.09,0.13,0.17,0.02,0.01,0.72,0.0,0.62,0.15,0.07
1991,9,9.0,80070.0,Waterburytown,10,0.16,0.37,0.25,0.69,0.04,...,0.08,0.32,0.18,0.08,0.06,0.78,0.0,0.91,0.28,0.23
1992,25,17.0,72600.0,Walthamcity,10,0.08,0.51,0.06,0.87,0.22,...,0.03,0.38,0.33,0.02,0.02,0.79,0.0,0.22,0.18,0.19

In [11]:
# Segundo escenario: Eliminar a las columnas con valores faltantes
df.dropna(axis = 1)

,state,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,...,PctForeignBorn,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn,ViolentCrimesPerPop
0,8,Lakewoodcity,1,0.19,0.33,0.02,0.90,0.12,0.17,0.34,...,0.12,0.42,0.50,0.51,0.64,0.12,0.26,0.20,0.32,0.20
1,53,Tukwilacity,1,0.00,0.16,0.12,0.74,0.45,0.07,0.26,...,0.21,0.50,0.34,0.60,0.52,0.02,0.12,0.45,0.00,0.67
2,24,Aberdeentown,1,0.00,0.42,0.49,0.56,0.17,0.04,0.39,...,0.14,0.49,0.54,0.67,0.56,0.01,0.21,0.02,0.00,0.43
3,34,Willingborotownship,1,0.04,0.77,1.00,0.08,0.12,0.10,0.51,...,0.19,0.30,0.73,0.64,0.65,0.02,0.39,0.28,0.00,0.12
4,42,Bethlehemtownship,1,0.01,0.55,0.02,0.95,0.09,0.05,0.38,...,0.11,0.72,0.64,0.61,0.53,0.04,0.09,0.02,0.00,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,12,TempleTerracecity,10,0.01,0.40,0.10,0.87,0.12,0.16,0.43,...,0.22,0.28,0.34,0.48,0.39,0.01,0.28,0.05,0.00,0.09
1990,6,Seasidecity,10,0.05,0.96,0.46,0.28,0.83,0.32,0.69,...,0.53,0.25,0.17,0.10,0.00,0.02,0.37,0.20,0.00,0.45
1991,9,Waterburytown,10,0.16,0.37,0.25,0.69,0.04,0.25,0.35,...,0.25,0.68,0.61,0.79,0.76,0.08,0.32,0.18,0.91,0.23
1992,25,Walthamcity,10,0.08,0.51,0.06,0.87,0.22,0.10,0.58,...,0.45,0.64,0.54,0.59,0.52,0.03,0.38,0.33,0.22,0.19
1993,6,Ontariocity,10,0.20,0.78,0.14,0.46,0.24,0.77,0.50,...,0.68,0.50,0.34,0.35,0.68,0.11,0.30,0.05,1.00,0.48

In [12]:
# Estas son las columnas con valorse faltantes
df.loc[:, df.isnull().sum().sort_values(ascending = False) != 0].columns

Index(['county', 'community', 'OtherPerCap', 'LemasSwornFT', 'LemasSwFTPerPop',
       'LemasSwFTFieldOps', 'LemasSwFTFieldPerPop', 'LemasTotalReq',
       'LemasTotReqPerPop', 'PolicReqPerOffic', 'PolicPerPop',
       'RacialMatchCommPol', 'PctPolicWhite', 'PctPolicBlack', 'PctPolicHisp',
       'PctPolicAsian', 'PctPolicMinor', 'OfficAssgnDrugUnits',
       'NumKindsDrugsSeiz', 'PolicAveOTWorked', 'PolicCars', 'PolicOperBudg',
       'LemasPctPolicOnPatr', 'LemasGangUnitDeploy', 'PolicBudgPerPop'],
      dtype='object')

In [13]:
# Entonces el dataset que usaremos para la regresión es:
df = df.dropna(axis = 1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Columns: 103 entries, state to ViolentCrimesPerPop
dtypes: float64(100), int64(2), object(1)
memory usage: 1.6+ MB

In [14]:
# Separemos las varialbes independientes (predictoras) y la variable dependiente (target)
X = df.drop(columns = ["ViolentCrimesPerPop"])
X = X.select_dtypes(include = ["float64"])
y = df["ViolentCrimesPerPop"]

In [15]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 99 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   population             1994 non-null   float64
 1   householdsize          1994 non-null   float64
 2   racepctblack           1994 non-null   float64
 3   racePctWhite           1994 non-null   float64
 4   racePctAsian           1994 non-null   float64
 5   racePctHisp            1994 non-null   float64
 6   agePct12t21            1994 non-null   float64
 7   agePct12t29            1994 non-null   float64
 8   agePct16t24            1994 non-null   float64
 9   agePct65up             1994 non-null   float64
 10  numbUrban              1994 non-null   float64
 11  pctUrban               1994 non-null   float64
 12  medIncome              1994 non-null   float64
 13  pctWWage               1994 non-null   float64
 14  pctWFarmSelf           1994 non-null   float64
 15  pctWInvInc             1994 non-null   float64
 16  pctWSocSec             1994 non-null   float64
 17  pctWPubAsst            1994 non-null   float64
 18  pctWRetire             1994 non-null   float64
 19  medFamInc              1994 non-null   float64
 20  perCapInc              1994 non-null   float64
 21  whitePerCap            1994 non-null   float64
 22  blackPerCap            1994 non-null   float64
 23  indianPerCap           1994 non-null   float64
 24  AsianPerCap            1994 non-null   float64
 25  HispPerCap             1994 non-null   float64
 26  NumUnderPov            1994 non-null   float64
 27  PctPopUnderPov         1994 non-null   float64
 28  PctLess9thGrade        1994 non-null   float64
 29  PctNotHSGrad           1994 non-null   float64
 30  PctBSorMore            1994 non-null   float64
 31  PctUnemployed          1994 non-null   float64
 32  PctEmploy              1994 non-null   float64
 33  PctEmplManu            1994 non-null   float64
 34  PctEmplProfServ        1994 non-null   float64
 35  PctOccupManu           1994 non-null   float64
 36  PctOccupMgmtProf       1994 non-null   float64
 37  MalePctDivorce         1994 non-null   float64
 38  MalePctNevMarr         1994 non-null   float64
 39  FemalePctDiv           1994 non-null   float64
 40  TotalPctDiv            1994 non-null   float64
 41  PersPerFam             1994 non-null   float64
 42  PctFam2Par             1994 non-null   float64
 43  PctKids2Par            1994 non-null   float64
 44  PctYoungKids2Par       1994 non-null   float64
 45  PctTeen2Par            1994 non-null   float64
 46  PctWorkMomYoungKids    1994 non-null   float64
 47  PctWorkMom             1994 non-null   float64
 48  NumIlleg               1994 non-null   float64
 49  PctIlleg               1994 non-null   float64
 50  NumImmig               1994 non-null   float64
 51  PctImmigRecent         1994 non-null   float64
 52  PctImmigRec5           1994 non-null   float64
 53  PctImmigRec8           1994 non-null   float64
 54  PctImmigRec10          1994 non-null   float64
 55  PctRecentImmig         1994 non-null   float64
 56  PctRecImmig5           1994 non-null   float64
 57  PctRecImmig8           1994 non-null   float64
 58  PctRecImmig10          1994 non-null   float64
 59  PctSpeakEnglOnly       1994 non-null   float64
 60  PctNotSpeakEnglWell    1994 non-null   float64
 61  PctLargHouseFam        1994 non-null   float64
 62  PctLargHouseOccup      1994 non-null   float64
 63  PersPerOccupHous       1994 non-null   float64
 64  PersPerOwnOccHous      1994 non-null   float64
 65  PersPerRentOccHous     1994 non-null   float64
 66  PctPersOwnOccup        1994 non-null   float64
 67  PctPersDenseHous       1994 non-null   float64
 68  PctHousLess3BR         1994 non-null   float64
 69  MedNumBR               1994 non-null   float64
 70  HousVacant             1994 non-null   float64
 71  PctHousOccup           1994 non-null   float64
 72  PctHousOwnOcc          1994 non-null   float64
 73  PctVacantBoarded       1994 non-null   float64
 74  PctVacMore6Mos         1994 non-null   float64
 75  MedYrHousBuilt         1994 non-null   float64
 76  PctHousNoPhone         1994 non-null   float64
 77  PctWOFullPlumb         1994 non-null   float64
 78  OwnOccLowQuart         1994 non-null   float64
 79  OwnOccMedVal           1994 non-null   float64
 80  OwnOccHiQuart          1994 non-null   float64
 81  RentLowQ               1994 non-null   float64
 82  RentMedian             1994 non-null   float64
 83  RentHighQ              1994 non-null   float64
 84  MedRent                1994 non-null   float64
 85  MedRentPctHousInc      1994 non-null   float64
 86  MedOwnCostPctInc       1994 non-null   float64
 87  MedOwnCostPctIncNoMtg  1994 non-null   float64
 88  NumInShelters          1994 non-null   float64
 89  NumStreet              1994 non-null   float64
 90  PctForeignBorn         1994 non-null   float64
 91  PctBornSameState       1994 non-null   float64
 92  PctSameHouse85         1994 non-null   float64
 93  PctSameCity85          1994 non-null   float64
 94  PctSameState85         1994 non-null   float64
 95  LandArea               1994 non-null   float64
 96  PopDens                1994 non-null   float64
 97  PctUsePubTrans         1994 non-null   float64
 98  LemasPctOfficDrugUn    1994 non-null   float64
dtypes: float64(99)
memory usage: 1.5 MB

## Primer Modelo

In [16]:
# Construyamos un modelo de regresión lineal
import statsmodels.api as sm

# Un requerimiento de statsmodels, agregar constante para el intercepto
X = sm.add_constant(X)

# Ajuste de una OLS
model = sm.OLS(y,X)
results = model.fit()
print(results.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     ViolentCrimesPerPop   R-squared:                       0.694
Model:                             OLS   Adj. R-squared:                  0.678
Method:                  Least Squares   F-statistic:                     43.34
Date:                 Sun, 15 Mar 2026   Prob (F-statistic):               0.00
Time:                         23:02:35   Log-Likelihood:                 1255.8
No. Observations:                 1994   AIC:                            -2312.
Df Residuals:                     1894   BIC:                            -1752.
Df Model:                           99
Covariance Type:             nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                     0.5593      0.203      2.749      0.006       0.160       0.958
population                0.1966      0.398      0.494      0.621      -0.584       0.977
householdsize            -0.0238      0.086     -0.275      0.784      -0.193       0.146
racepctblack              0.2060      0.051      4.020      0.000       0.105       0.307
racePctWhite             -0.0444      0.059     -0.755      0.451      -0.160       0.071
racePctAsian             -0.0132      0.034     -0.383      0.702      -0.081       0.054
racePctHisp               0.0534      0.054      0.997      0.319      -0.052       0.158
agePct12t21               0.1226      0.106      1.157      0.248      -0.085       0.330
agePct12t29              -0.2258      0.157     -1.441      0.150      -0.533       0.081
agePct16t24              -0.1476      0.165     -0.897      0.370      -0.470       0.175
agePct65up                0.0422      0.104      0.408      0.684      -0.161       0.246
numbUrban                -0.3207      0.388     -0.827      0.408      -1.081       0.440
pctUrban                  0.0477      0.016      3.043      0.002       0.017       0.078
medIncome                -0.1916      0.173     -1.107      0.268      -0.531       0.148
pctWWage                 -0.1998      0.089     -2.233      0.026      -0.375      -0.024
pctWFarmSelf              0.0469      0.020      2.323      0.020       0.007       0.086
pctWInvInc               -0.1727      0.068     -2.551      0.011      -0.305      -0.040
pctWSocSec                0.0824      0.107      0.768      0.443      -0.128       0.293
pctWPubAsst               0.0056      0.046      0.122      0.903      -0.085       0.096
pctWRetire               -0.0904      0.037     -2.449      0.014      -0.163      -0.018
medFamInc                 0.2839      0.161      1.767      0.077      -0.031       0.599
perCapInc                 0.0855      0.189      0.452      0.651      -0.285       0.456
whitePerCap              -0.3408      0.153     -2.232      0.026      -0.640      -0.041
blackPerCap              -0.0255      0.025     -1.000      0.317      -0.075       0.024
indianPerCap             -0.0350      0.019     -1.799      0.072      -0.073       0.003
AsianPerCap               0.0197      0.019      1.041      0.298      -0.017       0.057
HispPerCap                0.0502      0.024      2.108      0.035       0.003       0.097
NumUnderPov               0.1227      0.138      0.887      0.375      -0.149       0.394
PctPopUnderPov           -0.1800      0.063     -2.866      0.004      -0.303      -0.057
PctLess9thGrade          -0.1046      0.068     -1.540      0.124      -0.238       0.029
PctNotHSGrad              0.0595      0.096      0.619      0.536      -0.129       0.248
PctBSorMore               0.0576      0.078      0.742      0.458      -0.095       0.210
PctUnemployed             0.0011      0.041      0.027      0.978      -0.079       0.081
PctEmploy                 0.2481      0.079      3.138      0.002       0.093       0.403
PctEmplManu              -0.0642      0.032     -1.998      0.046      -0.127      -0.001
PctEmplProfServ          -0.0238      0.041     -0.582      0.560      -0.104       0.056
PctOccupManu              0.0697      0.055      1.267      0.205      -0.038       0.178
PctOccupMgmtProf          0.1038      0.087      1.200      0.230      -0.066       0.273
MalePctDivorce            0.4380      0.248      1.764      0.078      -0.049       0.925
MalePctNevMarr            0.2261      0.068      3.322      0.001       0.093       0.360
FemalePctDiv              0.1486      0.310      0.479      0.632      -0.460       0.757
TotalPctDiv              -0.5310      0.520     -1.022      0.307      -1.550       0.488
PersPerFam               -0.1410      0.169     -0.835      0.404      -0.472       0.190
PctFam2Par                0.0220      0.160      0.137      0.891      -0.292       0.336
PctKids2Par              -0.3292      0.156     -2.117      0.034      -0.634      -0.024
PctYoungKids2Par         -0.0269      0.048     -0.557      0.577      -0.122       0.068
PctTeen2Par              -0.0007      0.043     -0.017      0.986      -0.085       0.083
PctWorkMomYoungKids       0.0585      0.047      1.242      0.214      -0.034       0.151
PctWorkMom               -0.1844      0.054     -3.419      0.001      -0.290      -0.079
NumIlleg                 -0.1379      0.109     -1.268      0.205      -0.351       0.075
PctIlleg                  0.1193      0.048      2.506      0.012       0.026       0.213
NumImmig                 -0.1480      0.078     -1.895      0.058      -0.301       0.005
PctImmigRecent            0.0260      0.041      0.632      0.528      -0.055       0.107
PctImmigRec5              0.0245      0.067      0.369      0.712      -0.106       0.155
PctImmigRec8             -0.0721      0.077     -0.933      0.351      -0.224       0.079
PctImmigRec10             0.0413      0.060      0.691      0.490      -0.076       0.158
PctRecentImmig           -0.0363      0.122     -0.297      0.767      -0.276       0.204
PctRecImmig5             -0.1863      0.222     -0.841      0.401      -0.621       0.248
PctRecImmig8              0.4254      0.274      1.554      0.120      -0.111       0.962
PctRecImmig10            -0.2134      0.219     -0.974      0.330      -0.643       0.216
PctSpeakEnglOnly         -0.0374      0.070     -0.531      0.596      -0.176       0.101
PctNotSpeakEnglWell      -0.1579      0.068     -2.306      0.021      -0.292      -0.024
PctLargHouseFam           0.0586      0.227      0.259      0.796      -0.386       0.503
PctLargHouseOccup        -0.2087      0.237     -0.880      0.379      -0.674       0.256
PersPerOccupHous          0.6445      0.250      2.575      0.010       0.154       1.135
PersPerOwnOccHous        -0.0781      0.168     -0.465      0.642      -0.408       0.251
PersPerRentOccHous       -0.2605      0.081     -3.216      0.001      -0.419      -0.102
PctPersOwnOccup          -0.6629      0.359     -1.847      0.065      -1.367       0.041
PctPersDenseHous          0.2174      0.076      2.869      0.004       0.069       0.366
PctHousLess3BR            0.1085      0.059      1.847      0.065      -0.007       0.224
MedNumBR                  0.0304      0.019      1.562      0.118      -0.008       0.069
HousVacant                0.1598      0.073      2.185      0.029       0.016       0.303
PctHousOccup             -0.0475      0.031     -1.531      0.126      -0.108       0.013
PctHousOwnOcc             0.5523      0.375      1.471      0.141      -0.184       1.289
PctVacantBoarded          0.0500      0.021      2.331      0.020       0.008       0.092
PctVacMore6Mos           -0.0763      0.025     -3.033      0.002      -0.126      -0.027
MedYrHousBuilt           -0.0241      0.029     -0.830      0.406      -0.081       0.033
PctHousNoPhone            0.0120      0.035      0.341      0.733      -0.057       0.081
PctWOFullPlumb           -0.0169      0.020     -0.833      0.405      -0.057       0.023
OwnOccLowQuart           -0.3117      0.204     -1.531      0.126      -0.711       0.087
OwnOccMedVal              0.2262      0.307      0.736      0.462      -0.377       0.829
OwnOccHiQuart             0.0227      0.165      0.137      0.891      -0.301       0.346
RentLowQ                 -0.2319      0.067     -3.452      0.001      -0.364      -0.100
RentMedian               -0.0222      0.157     -0.142      0.887      -0.330       0.285
RentHighQ                -0.0760      0.086     -0.881      0.378      -0.245       0.093
MedRent                   0.3868      0.130      2.983      0.003       0.133       0.641
MedRentPctHousInc         0.0469      0.033      1.437      0.151      -0.017       0.111
MedOwnCostPctInc         -0.0494      0.035     -1.432      0.152      -0.117       0.018
MedOwnCostPctIncNoMtg    -0.0831      0.025     -3.388      0.001      -0.131      -0.035
NumInShelters             0.1382      0.064      2.148      0.032       0.012       0.264
NumStreet                 0.1823      0.047      3.862      0.000       0.090       0.275
PctForeignBorn            0.1320      0.090      1.467      0.142      -0.044       0.309
PctBornSameState          0.0050      0.042      0.121      0.904      -0.077       0.087
PctSameHouse85           -0.0208      0.058     -0.360      0.719      -0.134       0.092
PctSameCity85             0.0217      0.038      0.569      0.569      -0.053       0.097
PctSameState85            0.0160      0.043      0.373      0.709      -0.068       0.100
LandArea                  0.0255      0.049      0.518      0.604      -0.071       0.122
PopDens                  -0.0106      0.030     -0.349      0.727      -0.070       0.049
PctUsePubTrans           -0.0402      0.023     -1.736      0.083      -0.086       0.005
LemasPctOfficDrugUn       0.0262      0.015      1.695      0.090      -0.004       0.057
==============================================================================
Omnibus:                      383.345   Durbin-Watson:                   2.004
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1245.537
Skew:                           0.952   Prob(JB):                    3.43e-271
Kurtosis:                       6.372   Cond. No.                         914.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [17]:
# Obtengamos los p-values de cada variable en model
results.pvalues

const                  0.006028
population             0.621230
householdsize          0.783542
racepctblack           0.000061
racePctWhite           0.450534
                         ...
PctSameState85         0.709235
LandArea               0.604185
PopDens                0.727348
PctUsePubTrans         0.082692
LemasPctOfficDrugUn    0.090285
Length: 100, dtype: float64

In [18]:
# Obtener los nombres de las variables cuyo p-values sea menor a 5%
#significant_vars = results.pvalues[results.pvalues < 0.05].index
summary_table = pd.DataFrame({
    "coef": results.params,
    "pvalue": results.pvalues
})

significant = summary_table[summary_table["pvalue"] < 0.05]
significant

                           coef    pvalue
const                  0.559274  0.006028
racepctblack           0.206004  0.000061
pctUrban               0.047656  0.002377
pctWWage              -0.199779  0.025682
pctWFarmSelf           0.046859  0.020308
pctWInvInc            -0.172693  0.010807
pctWRetire            -0.090352  0.014422
whitePerCap           -0.340850  0.025729
HispPerCap             0.050158  0.035201
PctPopUnderPov        -0.180034  0.004204
PctEmploy              0.248146  0.001728
PctEmplManu           -0.064196  0.045838
MalePctNevMarr         0.226059  0.000911
PctKids2Par           -0.329246  0.034363
PctWorkMom            -0.184439  0.000641
PctIlleg               0.119304  0.012309
PctNotSpeakEnglWell   -0.157861  0.021202
PersPerOccupHous       0.644457  0.010085
PersPerRentOccHous    -0.260508  0.001324
PctPersDenseHous       0.217399  0.004164
HousVacant             0.159836  0.028984
PctVacantBoarded       0.049987  0.019882
PctVacMore6Mos        -0.076268  0.002458
RentLowQ              -0.231856  0.000568
MedRent                0.386793  0.002887
MedOwnCostPctIncNoMtg -0.083089  0.000719
NumInShelters          0.138231  0.031825
NumStreet              0.182320  0.000116

In [19]:
# Variables significativas
significant_vars = list(significant.index)
len(significant_vars)

28

## Segundo Modelo

Usando las variables significativas del primer modelo

In [20]:
# Seleccionemos solo las variables significativas
X_reduced = X[significant_vars]

# Ajustemos un segundo modelo de regresión lineal (reducido)
model_reduced = sm.OLS(y, X_reduced)
results_reduced = model_reduced.fit()
print(results_reduced.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     ViolentCrimesPerPop   R-squared:                       0.673
Model:                             OLS   Adj. R-squared:                  0.668
Method:                  Least Squares   F-statistic:                     149.7
Date:                 Sun, 15 Mar 2026   Prob (F-statistic):               0.00
Time:                         23:02:49   Log-Likelihood:                 1189.6
No. Observations:                 1994   AIC:                            -2323.
Df Residuals:                     1966   BIC:                            -2167.
Df Model:                           27
Covariance Type:             nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                     0.7232      0.061     11.798      0.000       0.603       0.843
racepctblack              0.1838      0.028      6.505      0.000       0.128       0.239
pctUrban                  0.0336      0.009      3.795      0.000       0.016       0.051
pctWWage                 -0.2351      0.051     -4.570      0.000      -0.336      -0.134
pctWFarmSelf              0.0284      0.019      1.492      0.136      -0.009       0.066
pctWInvInc               -0.1083      0.050     -2.167      0.030      -0.206      -0.010
pctWRetire               -0.1149      0.031     -3.676      0.000      -0.176      -0.054
whitePerCap              -0.0994      0.043     -2.303      0.021      -0.184      -0.015
HispPerCap                0.0425      0.023      1.855      0.064      -0.002       0.087
PctPopUnderPov           -0.1796      0.042     -4.317      0.000      -0.261      -0.098
PctEmploy                 0.1081      0.053      2.039      0.042       0.004       0.212
PctEmplManu              -0.0435      0.017     -2.500      0.013      -0.078      -0.009
MalePctNevMarr           -0.0057      0.030     -0.192      0.848      -0.064       0.053
PctKids2Par              -0.4258      0.061     -7.030      0.000      -0.545      -0.307
PctWorkMom               -0.1258      0.026     -4.898      0.000      -0.176      -0.075
PctIlleg                  0.1489      0.040      3.680      0.000       0.070       0.228
PctNotSpeakEnglWell      -0.0604      0.037     -1.635      0.102      -0.133       0.012
PersPerOccupHous         -0.0052      0.051     -0.102      0.918      -0.106       0.095
PersPerRentOccHous       -0.0685      0.043     -1.590      0.112      -0.153       0.016
PctPersDenseHous          0.2588      0.051      5.124      0.000       0.160       0.358
HousVacant                0.1466      0.033      4.467      0.000       0.082       0.211
PctVacantBoarded          0.0568      0.020      2.872      0.004       0.018       0.096
PctVacMore6Mos           -0.0354      0.022     -1.610      0.107      -0.078       0.008
RentLowQ                 -0.2281      0.053     -4.308      0.000      -0.332      -0.124
MedRent                   0.3125      0.059      5.273      0.000       0.196       0.429
MedOwnCostPctIncNoMtg    -0.0918      0.020     -4.614      0.000      -0.131      -0.053
NumInShelters            -0.0239      0.054     -0.446      0.656      -0.129       0.081
NumStreet                 0.1654      0.044      3.733      0.000       0.078       0.252
==============================================================================
Omnibus:                      394.788   Durbin-Watson:                   2.023
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1272.456
Skew:                           0.982   Prob(JB):                    4.89e-277
Kurtosis:                       6.385   Cond. No.                         68.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [21]:
# Comparemos los resultados de estos modelos
print("R² Original: ", results.rsquared)
print("R² reducido: ", results_reduced.rsquared)
print()
print("Adj R² Original: ", results.rsquared_adj)
print("Adj R² reducido: ", results_reduced.rsquared_adj)
print()
print("AIC Original: ", results.aic)
print("AIC reducido: ", results_reduced.aic)
print()
print("BIC Original: ", results.bic)
print("BIC reducido: ", results_reduced.bic)

R² Original:  0.6937465628945809
R² reducido:  0.6727506862582984

Adj R² Original:  0.6777385954851636
Adj R² reducido:  0.6682564179617441

AIC Original:  -2311.503042965238
AIC reducido:  -2323.282253412701

BIC Original:  -1751.7132479130596
BIC reducido:  -2166.541110798091

In [ ]:
# R² Original:  0.6937465628945809
# R² reducido:  0.6727506862582984

# La pérdida de poder explicativo (69.4 - 67.3) aprox. 2%, es muy pequeña a pesar
# de que se ha eliminado una gran cantidad de variables (99-27 = 72).

# Esto nos dice que muchas variables del modelo orifinal, aportaban muy poca información

In [ ]:
# AIC Original:  -2311.503042965238
# AIC reducido:  -2323.282253412701

# REGLA: Menor AIC ==> "Mejor modelo"

# Conclusión: El modelo reducido es preferible según AIC.
# Esto es, que el equilibrio entre el ajuste del modelo y la complejidad es mejor
# en el modelo reducido.

In [ ]:
# BIC Original:  -1751.7132479130596
# BIC reducido:  -2166.541110798091

# REGLA: Menor BIC ==> "Mejor modelo"

# El modelo reducido tiene un BIC mucho menor, lo cual es indicativo que el modelo
# reducido tiene una mejora muy fuerte en parsimonía ==> Lo cual implica que hay
# un menor riesgo de sobreajuste.

In [ ]:
# EN CONCLUSIÓN:
# --------------
    # Usa 27 variables en lugar de 99
    # Mantiene casi el mismo poder explicativo (R²)
    # Mejora AIC
    # Mejora BIC
# Esto nos dice que el modelo reducido es un modelo estadísticamente más
# eficiente.

# Se da el principio de OCCAM: Dos modelos con la capacidad predictiva similar,
# preferimos el modelo más simple.

In [22]:
# Coeficientes y p-values del modelo original
significant

                           coef    pvalue
const                  0.559274  0.006028
racepctblack           0.206004  0.000061
pctUrban               0.047656  0.002377
pctWWage              -0.199779  0.025682
pctWFarmSelf           0.046859  0.020308
pctWInvInc            -0.172693  0.010807
pctWRetire            -0.090352  0.014422
whitePerCap           -0.340850  0.025729
HispPerCap             0.050158  0.035201
PctPopUnderPov        -0.180034  0.004204
PctEmploy              0.248146  0.001728
PctEmplManu           -0.064196  0.045838
MalePctNevMarr         0.226059  0.000911
PctKids2Par           -0.329246  0.034363
PctWorkMom            -0.184439  0.000641
PctIlleg               0.119304  0.012309
PctNotSpeakEnglWell   -0.157861  0.021202
PersPerOccupHous       0.644457  0.010085
PersPerRentOccHous    -0.260508  0.001324
PctPersDenseHous       0.217399  0.004164
HousVacant             0.159836  0.028984
PctVacantBoarded       0.049987  0.019882
PctVacMore6Mos        -0.076268  0.002458
RentLowQ              -0.231856  0.000568
MedRent                0.386793  0.002887
MedOwnCostPctIncNoMtg -0.083089  0.000719
NumInShelters          0.138231  0.031825
NumStreet              0.182320  0.000116

In [23]:
# Obtener los nombres de las variables cuyo p-values
summary_table_reduced = pd.DataFrame({
    "coef": results_reduced.params,
    "pvalue": results_reduced.pvalues
})

significant_reduced = summary_table_reduced.copy()
significant_reduced

                           coef        pvalue
const                  0.723168  4.367029e-31
racepctblack           0.183841  9.832202e-11
pctUrban               0.033576  1.519178e-04
pctWWage              -0.235063  5.173692e-06
pctWFarmSelf           0.028384  1.357603e-01
pctWInvInc            -0.108347  3.037171e-02
pctWRetire            -0.114891  2.431367e-04
whitePerCap           -0.099404  2.135645e-02
HispPerCap             0.042511  6.379943e-02
PctPopUnderPov        -0.179640  1.658285e-05
PctEmploy              0.108093  4.154209e-02
PctEmplManu           -0.043469  1.250887e-02
MalePctNevMarr        -0.005711  8.475394e-01
PctKids2Par           -0.425834  2.847643e-12
PctWorkMom            -0.125752  1.048858e-06
PctIlleg               0.148903  2.392181e-04
PctNotSpeakEnglWell   -0.060357  1.022096e-01
PersPerOccupHous      -0.005239  9.184289e-01
PersPerRentOccHous    -0.068537  1.120893e-01
PctPersDenseHous       0.258837  3.277554e-07
HousVacant             0.146558  8.390804e-06
PctVacantBoarded       0.056775  4.124701e-03
PctVacMore6Mos        -0.035381  1.074860e-01
RentLowQ              -0.228128  1.725102e-05
MedRent                0.312459  1.488466e-07
MedOwnCostPctIncNoMtg -0.091755  4.207093e-06
NumInShelters         -0.023858  6.559003e-01
NumStreet              0.165389  1.949573e-04

# Regularización Lasso (L1)
 usando sklearn

In [24]:
from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv(
    "communities.data",
    header = None,
    na_values = "?"
)

columns = []
with open("communities.names") as f:
  for line in f:
    if line.startswith("@attribute"):
      columns.append(line.split()[1])
df.columns = columns
df = df.dropna(axis = 1)
X = df.drop(columns = ["ViolentCrimesPerPop"])
X = X.select_dtypes(include = ["float64"])
y = df["ViolentCrimesPerPop"]

In [25]:
# Estandarización (Obligatorio para Lasso)
scale = StandardScaler()
X_scaled_data = scale.fit_transform(X)

# Convertir X_scaled_data a un dataframe para mantener los nombres de las columnas
X_scaled = pd.DataFrame(X_scaled_data, columns = X.columns, index = X.index)

# Lista de valores alpha a probar
mis_alphas = np.logspace(-4, 1, 20)

# Consideremos 10 validaciones cruzadas
lasso_cv = LassoCV(alphas = mis_alphas,
                   cv = 10,
                   max_iter =10000,
                   tol = 1e-5,
                   random_state = 666,
                   fit_intercept=True)

# Entrenamos el modelo
lasso_cv.fit(X_scaled, y)

LassoCV(alphas=array([1.00000000e-04, 1.83298071e-04, 3.35981829e-04, 6.15848211e-04,
       1.12883789e-03, 2.06913808e-03, 3.79269019e-03, 6.95192796e-03,
       1.27427499e-02, 2.33572147e-02, 4.28133240e-02, 7.84759970e-02,
       1.43844989e-01, 2.63665090e-01, 4.83293024e-01, 8.85866790e-01,
       1.62377674e+00, 2.97635144e+00, 5.45559478e+00, 1.00000000e+01]),
        cv=10, max_iter=10000, random_state=666, tol=1e-05)

In [26]:
# dir(lasso_cv)
# El mejor alpha
best_alpha = lasso_cv.alpha_
best_alpha

np.float64(0.0003359818286283781)

In [27]:
# Coeficientes del modelo
coeficients = lasso_cv.coef_
intercept = lasso_cv.intercept_

# Crearemos un dataframe para visualizar los coeficientes
results_df = pd.DataFrame({
    "Variable": X.columns.tolist(),
    "Coeficiente": coeficients

})

results_df.sort_values(by = "Coeficiente", ascending = False)

            Variable  Coeficiente
63  PersPerOccupHous     0.051979
2       racepctblack     0.049238
84           MedRent     0.048188
67  PctPersDenseHous     0.033957
49          PctIlleg     0.033152
..               ...          ...
13          pctWWage    -0.028205
27    PctPopUnderPov    -0.031628
7        agePct12t29    -0.035632
81          RentLowQ    -0.042762
43       PctKids2Par    -0.055850

[99 rows x 2 columns]

In [28]:
# Veamos aquellas variables cuyo coeficiente es cero (Lasso)
results_df[results_df["Coeficiente"] == 0].shape

# La técnica de regularización Lasso a vuelto 29 coeficientes

(29, 2)

In [29]:
# Filtrar las variables seleccionadas (Coeficiente != 0)
selected_var = results_df[results_df["Coeficiente"] != 0].sort_values(by = "Coeficiente", ascending = False, key = abs)
selected_var

            Variable  Coeficiente
43       PctKids2Par    -0.055850
63  PersPerOccupHous     0.051979
2       racepctblack     0.049238
84           MedRent     0.048188
81          RentLowQ    -0.042762
..               ...          ...
77    PctWOFullPlumb    -0.001975
9         agePct65up     0.001734
75    MedYrHousBuilt    -0.001654
51    PctImmigRecent     0.000929
94    PctSameState85     0.000055

[70 rows x 2 columns]

In [30]:
# Evaluación del rendimiento
y_pred = lasso_cv.predict(X_scaled)
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

print("Métricas de Ajuste - Lasso:")
print(f"R2: {r2:.6f}")
print(f"MSE: {mse*100:.6f}%")
#

Métricas de Ajuste - Lasso:
R2: 0.688740
MSE: 1.688734%

# Regularización Ridge (L2)

In [31]:
from sklearn.linear_model import RidgeCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv(
    "communities.data",
    header = None,
    na_values = "?"
)

columns = []
with open("communities.names") as f:
  for line in f:
    if line.startswith("@attribute"):
      columns.append(line.split()[1])
df.columns = columns
df = df.dropna(axis = 1)
X = df.drop(columns = ["ViolentCrimesPerPop"])
X = X.select_dtypes(include = ["float64"])
y = df["ViolentCrimesPerPop"]

In [32]:
# Estandarización (Obligatorio para Ridge)
scale = StandardScaler()
X_scaled_data = scale.fit_transform(X)

# Convertir X_scaled_data a un dataframe para mantener los nombres de las columnas
X_scaled = pd.DataFrame(X_scaled_data, columns = X.columns, index = X.index)

# Lista de valores alpha a probar
mis_alphas = np.logspace(-4, 1, 20)

# Consideremos 10 validaciones cruzadas
ridge_cv = RidgeCV(alphas = mis_alphas,
                   cv = 10)

# Entrenamos el modelo
ridge_cv.fit(X_scaled, y)

RidgeCV(alphas=array([1.00000000e-04, 1.83298071e-04, 3.35981829e-04, 6.15848211e-04,
       1.12883789e-03, 2.06913808e-03, 3.79269019e-03, 6.95192796e-03,
       1.27427499e-02, 2.33572147e-02, 4.28133240e-02, 7.84759970e-02,
       1.43844989e-01, 2.63665090e-01, 4.83293024e-01, 8.85866790e-01,
       1.62377674e+00, 2.97635144e+00, 5.45559478e+00, 1.00000000e+01]),
        cv=10)

In [33]:
# El mejor alpha
best_alpha = ridge_cv.alpha_
best_alpha

np.float64(10.0)

In [34]:
# Coeficientes del modelo
coeficients = ridge_cv.coef_
intercept = ridge_cv.intercept_

# Crearemos un dataframe para visualizar los coeficientes
results_df = pd.DataFrame({
    "Variable": X.columns.tolist(),
    "Coeficiente": coeficients

})

results_df.sort_values(by = "Coeficiente", ascending = False)

            Variable  Coeficiente
63  PersPerOccupHous     0.065419
84           MedRent     0.056120
2       racepctblack     0.049428
67  PctPersDenseHous     0.040061
37    MalePctDivorce     0.037015
..               ...          ...
7        agePct12t29    -0.036558
66   PctPersOwnOccup    -0.038037
21       whitePerCap    -0.044376
81          RentLowQ    -0.045685
43       PctKids2Par    -0.047380

[99 rows x 2 columns]

In [38]:
# Veamos los coeficientes más pequeños en valor absoluto
results_df.reindex(results_df["Coeficiente"].abs().sort_values().index).head(10)

            Variable  Coeficiente
0         population     0.000161
96           PopDens    -0.001066
52      PctImmigRec5    -0.001204
45       PctTeen2Par    -0.001227
91  PctBornSameState    -0.001266
12         medIncome    -0.001398
1      householdsize     0.001402
58     PctRecImmig10    -0.001445
92    PctSameHouse85    -0.001680
17       pctWPubAsst     0.001680

In [36]:
# Filtrar las variables seleccionadas (Coeficiente != 0)
selected_var = results_df[results_df["Coeficiente"] != 0].sort_values(by = "Coeficiente", ascending = False, key = abs)
selected_var

            Variable  Coeficiente
63  PersPerOccupHous     0.065419
84           MedRent     0.056120
2       racepctblack     0.049428
43       PctKids2Par    -0.047380
81          RentLowQ    -0.045685
..               ...          ...
91  PctBornSameState    -0.001266
45       PctTeen2Par    -0.001227
52      PctImmigRec5    -0.001204
96           PopDens    -0.001066
0         population     0.000161

[99 rows x 2 columns]

In [39]:
# Evaluación del rendimiento
y_pred = ridge_cv.predict(X_scaled)
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

print("Métricas de Ajuste - Ridge:")
print(f"R2: {r2:.6f}")
print(f"MSE: {mse*100:.6f}%")

Métricas de Ajuste - Ridge:
R2: 0.691819
MSE: 1.672026%

# Regularización ElasticNet

https://hastie.su.domains/Papers/elasticnet.pdf

In [43]:
# Para las Validaciones Cruzadas (CV)
from sklearn.model_selection import KFold

df = pd.read_csv(
    "communities.data",
    header = None,
    na_values = "?"
)

columns = []

with open("communities.names") as f:
  for line in f:
    if line.startswith("@attribute"):
      columns.append(line.split()[1])

df.columns = columns

df = df.dropna(axis = 1)

X = df.drop(columns = ["ViolentCrimesPerPop"])
X = X.select_dtypes(include = ["float64"])
y = df["ViolentCrimesPerPop"]

In [42]:
# Estandarización e Intercepto
scaler = StandardScaler()
X_scaled_data = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled_data, columns = X.columns, index = X.index)

# Añadimos la constante para el intercepto: Requerimiento para statsmodels
X_scaled_const = sm.add_constant(X_scaled)

# Búsqueda de los mejores hiperparámetros
def find_best_elastic_net_params(X, y, alphas, l1_weights, n_splits = 5):
    kf = KFold(n_splits = n_splits, shuffle = True, random_state = 666)

    best_alpha = None
    best_l1_wt = None
    min_mse = float("inf")

    print("Buscando mejores parámetros (alpha y l1_ratio) mediante CV")

    # Estrategia de Grid Search
    for alpha in alphas:
        for l1_wt in l1_weights:
            mse_scores = []

            for train_idx, test_idx in kf.split(X):
                X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
                y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

                # Escalado dentro de cada fold
                scaler = StandardScaler()
                X_train_scaled = scaler.fit_transform(X_train)
                X_test_scaled = scaler.transform(X_test)

                X_train_scaled = pd.DataFrame(X_train_scaled, columns = X.columns, index = X_train.index)
                X_test_scaled = pd.DataFrame(X_test_scaled, columns = X.columns, index = X_test.index)

                # Añadimos constante
                X_train_const = sm.add_constant(X_train_scaled, has_constant = "add")
                X_test_const = sm.add_constant(X_test_scaled, has_constant = "add")

                try:
                    # Definir modelo sobre el fold de entrenamiento
                    modelo = sm.OLS(y_train, X_train_const)

                    # Ajustar elastic net
                    results = modelo.fit_regularized(
                        method = "elastic_net",
                        alpha = alpha,
                        L1_wt = l1_wt,
                        maxiter = 10000
                    )

                    y_pred = results.predict(X_test_const)
                    mse = mean_squared_error(y_test, y_pred)
                    mse_scores.append(mse)

                except Exception:
                    mse_scores.append(float("inf"))

            avg_mse = np.mean(mse_scores)

            if avg_mse < min_mse:
                min_mse = avg_mse
                best_alpha = alpha
                best_l1_wt = l1_wt

    return best_alpha, best_l1_wt, min_mse

In [ ]:
# Definamos rangos de búsqueda
alphas_grid = np.logspace(-4, 1, 20)
l1_weights_grid = np.linspace(0, 1, num = 10)

best_alpha, best_l1_wt, cv_mse = find_best_elastic_net_params(X, y, alphas_grid, l1_weights_grid)

print("Mejor alpha:", best_alpha)
print("Mejor L1_wt:", best_l1_wt)
print("CV MSE:", cv_mse)

Buscando mejores parámetros (alpha y l1_ratio) mediante CV

In [ ]:
# Estandarización final
scaler = StandardScaler()
X_scaled_data = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled_data, columns = X.columns, index = X.index)

# Añadimos la constante para el intercepto
X_scaled_const = sm.add_constant(X_scaled, has_constant = "add")

# Entrenamiento final de ElasticNet
model_en = sm.OLS(y, X_scaled_const)
result_en = model_en.fit_regularized(
    method = "elastic_net",
    alpha = best_alpha,
    L1_wt = best_l1_wt,
    maxiter = 10000
)

result_en.params

In [ ]:
# Entrenamiento final de ElasticNet
model_en = sm.OLS(y, X_scaled_const)
result_en = model_en.fit_regularized(
    method = "elastic_net",
    alpha = best_alpha,
    L1_wt = best_l1_wt,
    maxiter = 10000
)

result_en.summary()

In [ ]:
coef_df = pd.DataFrame({
    "Variable": X_scaled_const.columns,
    "Coeficiente": result_en.params
})

coef_df.sort_values(by = "Coeficiente", key = abs, ascending = False)

In [ ]:
y_pred = result_en.predict(X_scaled_const)

mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

print("Métricas de Ajuste - Elastic Net:")
print(f"R2: {r2:.6f}")
print(f"MSE: {mse*100:.6f}%")